### ISSUE TITLE
Unable to Deploy React + Java Spring Application

### ISSUE THREAD

**Issue by eckad158** [g00glen00b/dimitr.im#100]
**Blogpost**:

I have a question about [Bundling-react-spring-boot](https://dimitr.im/bundling-react-spring-boot).
It seems as if i managed to build the war file correctly however i am having a lot of trouble to deploying the war file. 

I try to deploy it using the docker tomcat:jre17-temurin image template.
The Tomcat process seems to extract and deploy the war file just fine, however the actual Frontend + Backend is not reachable.

It seems as if my Application / Servlet is not recognized and started.
This is what my Spring-Servletinitializer looks like:

`    
    import javax.servlet.ServletContext;
    import javax.servlet.ServletRegistration;
    
    import org.springframework.boot.builder.SpringApplicationBuilder;
    import org.springframework.boot.web.servlet.support.SpringBootServletInitializer;
    import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;
    import org.springframework.web.servlet.DispatcherServlet;
    
    public class ServletInitializer extends SpringBootServletInitializer {
	    @Override
	    public void onStartup(ServletContext container) {
		    // Register any @Configuration classes. Could use xml instead but that's no fun.
		    AnnotationConfigWebApplicationContext ctx = new AnnotationConfigWebApplicationContext();
		    ctx.register(SecurityConfig.class, ItDashBoard.class, WebConfig.class);

		    // Create and configure the dispatcher servlet
		    ServletRegistration.Dynamic dispatcher = container.addServlet("dispatcher", new DispatcherServlet(ctx));
		    dispatcher.setLoadOnStartup(1);
		    dispatcher.addMapping("/");
	    }
    
	    @Override
	    protected SpringApplicationBuilder configure(SpringApplicationBuilder application) {
		    return application.sources(ItDashBoard.class);
	    }
    }
`

// The ITDashBoard.class is my @SpringBootApplication
// The WebConfig is yours (1:1)
// The SecurityConfig permits all requests

Can you maybe give me a hint what i am doing wrong ?

**Comment by g00glen00b** [comment]
Hi! I'm not familiar with your setup. Do you use the WAR-file in a traditional way (as in deployed on a servlet container like Tomcat), or do you run it as a standalone application (if so, is there a reason why you use a WAR-file in stead of a JAR-file)?

Do you think the problem is within your Docker-setup or within your Java/Spring boot setup? Does the applicaiton (frontend and backend) work properly if you run it locally without Docker? If it's Docker related, I probably need more information about how you generate your Docker image (Dockerfile).

**Comment by eckad158** [comment]
this is what the docker log looks like:

25-Mar-2022 15:59:08.136 INFO [main] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
15:59:08.261 [main] INFO com.fleisck.itdashboard.ItDashBoard - #### onStartup ausgeführt ####
15:59:08.274 [main] INFO org.springframework.web.servlet.DispatcherServlet - Initializing Servlet 'dispatcher'
15:59:08.289 [main] DEBUG org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Refreshing WebApplicationContext for namespace 'dispatcher-servlet'
15:59:08.331 [main] DEBUG org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Registering component classes: [class com.woehlk.itdashboard.WebConfig]
15:59:08.355 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalConfigurationAnnotationProcessor'
15:59:08.451 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.event.internalEventListenerProcessor'
15:59:08.453 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.event.internalEventListenerFactory'
15:59:08.454 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalAutowiredAnnotationProcessor'
15:59:08.456 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalCommonAnnotationProcessor'
15:59:08.459 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'org.springframework.context.annotation.internalPersistenceAnnotationProcessor'
15:59:08.464 [main] DEBUG org.springframework.ui.context.support.UiApplicationContextUtils - Unable to locate ThemeSource with name 'themeSource': using default [org.springframework.ui.context.support.ResourceBundleThemeSource@43ca45af]
15:59:08.465 [main] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Creating shared instance of singleton bean 'webConfig'
15:59:08.497 [main] DEBUG _org.springframework.web.servlet.HandlerMapping.Mappings - 'org.springframework.web.servlet.handler.BeanNameUrlHandlerMapping' {}
15:59:08.778 [main] DEBUG org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter - ControllerAdvice beans: none
15:59:08.832 [main] DEBUG org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver - ControllerAdvice beans: none
15:59:08.852 [main] DEBUG org.springframework.jndi.JndiTemplate - Looking up JNDI object with name [java:comp/env/spring.liveBeansView.mbeanDomain]
15:59:08.854 [main] DEBUG org.springframework.jndi.JndiLocatorDelegate - Converted JNDI name [java:comp/env/spring.liveBeansView.mbeanDomain] not found - trying original name [spring.liveBeansView.mbeanDomain]. javax.naming.NameNotFoundException: Name [spring.liveBeansView.mbeanDomain] is not bound in this Context. Unable to find [spring.liveBeansView.mbeanDomain].
15:59:08.854 [main] DEBUG org.springframework.jndi.JndiTemplate - Looking up JNDI object with name [spring.liveBeansView.mbeanDomain]
15:59:08.854 [main] DEBUG org.springframework.jndi.JndiPropertySource - JNDI lookup for name [spring.liveBeansView.mbeanDomain] threw NamingException with message: Name [spring.liveBeansView.mbeanDomain] is not bound in this Context. Unable to find [spring.liveBeansView.mbeanDomain].. Returning null.
15:59:08.866 [main] DEBUG org.springframework.web.servlet.DispatcherServlet - enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
15:59:08.866 [main] INFO org.springframework.web.servlet.DispatcherServlet - Completed initialization in 592 ms
25-Mar-2022 15:59:08.876 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/itdashboard-backend-1.0.war] has finished in [3,042] ms
25-Mar-2022 15:59:08.879 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
25-Mar-2022 15:59:08.889 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [3143] milliseconds

**Comment by g00glen00b** [comment]
Considering that your logs do contain Spring-related messages it seems like your application does start up.
Maybe you're calling your application from the wrong path? It should be http://server:8080/itdashboard-backend-1.0/ if I'm not mistaken.

**Comment by eckad158** [comment]
First of all i really want to give you a big THANK YOU for the time you spend on writing the article and having a look at my problem. I really appreciate your work!

If i access the server on http://server:8080/ nothing happens (in the logs).
When i acces the server on http://server:8080/itdashboard-backend-1.0/ the logs say No mapping for GET /it-dashboard-1.0/

`unable to find [spring.liveBeansView.mbeanDomain].. Returning null.
08:36:55.941 [main] DEBUG org.springframework.web.servlet.DispatcherServlet - enableLoggingRequestDetails='false': request parameters and headers will be masked to prevent unsafe logging of potentially sensitive data
08:36:55.945 [main] INFO org.springframework.web.servlet.DispatcherServlet - Completed initialization in 626 ms
31-Mar-2022 08:36:55.954 INFO [main] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/itdashboard-backend-1.0.war] has finished in [2,900] ms
31-Mar-2022 08:36:55.957 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
31-Mar-2022 08:36:55.965 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in [2996] milliseconds
/itdashboard-backend-1.008:37:20.633 [http-nio-8080-exec-1] DEBUG org.springframework.web.servlet.DispatcherServlet - GET "/itdashboard-backend-1.0/", parameters={}
08:37:20.646 [http-nio-8080-exec-1] WARN org.springframework.web.servlet.PageNotFound - No mapping for GET /itdashboard-backend-1.0/
08:37:20.649 [http-nio-8080-exec-1] DEBUG org.springframework.web.servlet.DispatcherServlet - Completed 404 NOT_FOUND
08:37:25.516 [http-nio-8080-exec-3] DEBUG org.springframework.web.servlet.DispatcherServlet - GET "/itdashboard-backend-1.0/", parameters={}
08:37:25.517 [http-nio-8080-exec-3] WARN org.springframework.web.servlet.PageNotFound - No mapping for GET /itdashboard-backend-1.0/
08:37:25.517 [http-nio-8080-exec-3] DEBUG org.springframework.web.servlet.DispatcherServlet - Completed 404 NOT_FOUND
08:37:58.379 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.DispatcherServlet - GET "/itdashboard-backend-1.0/index.html", parameters={}
08:37:58.380 [http-nio-8080-exec-6] WARN org.springframework.web.servlet.PageNotFound - No mapping for GET /itdashboard-backend-1.0/index.html
08:37:58.380 [http-nio-8080-exec-6] DEBUG org.springframework.web.servlet.DispatcherServlet - Completed 404 NOT_FOUND
`
**It seems as  if the Webconfig / Controller Files are not properly registered in the app. But i have no clue why**

This what the WebConfig looks like:

`package com.fleisck.itdashboard;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
public class WebConfig implements WebMvcConfigurer {
	
	@Override
	public void addViewControllers(ViewControllerRegistry registry) {
		registry.addViewController("/").setViewName("forward:/index.html");
		registry.addViewController("/{x:[\\w\\-]+}").setViewName("forward:/index.html");
		registry.addViewController("/{x:^(?!api$).*$}/**/{y:[\\w\\-]+}").setViewName("forward:/index.html");
	}
}`

And my ApiController has a simple @RestController annotation + some PostMappings and GetMapping

**Comment by g00glen00b** [comment]
That's weird behaviour. Does your code also work if you build the WAR file and run it in a servlet container on your machine rather than within a Docker container?
